import { title } from "process";

export const Goods = [
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
  {
    image: "/Good/Aothun.jpg",
    title: "Áo Thun Cổ Tròn Nam",
    badges: ["Rẻ Vô Địch"],
    price: 50000,
  },
];
